version: "3.9"
services:
  django_back:
    container_name: django_back
    build:
      context: .
      dockerfile: ./back_end/Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./back_end:/mentors-back