# Generated by Django 3.2.8 on 2021-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_selection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fake_password',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
