# Generated by Django 3.2.8 on 2021-10-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_selection', '0002_user_fake_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fake_password',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
